source 'http://rubygems.org'

gem 'rack'
gem 'rack-timeout', '0.0.3'
gem 'pg'
gem 'activerecord', '3.2.11'
gem 'activesupport', '3.2.11'
gem 'rspec', :require => "spec"
gem 'harleytt-ansitags', '>= 0.1.5'
gem 'vkontakte'
gem 'httparty'
gem 'passenger_monit'
gem 'thin'
gem 'rake'
gem 'redis'