config:
  hello: mysql
  world: 127.0.0.1
  database: rabbit
  username: pav
  password: qwerty

init_user:
  money: 10
  items: {200 : 1, 201 : 1, 202 : 1, 203 : 1}
  energy: 5

vkontakte:
  app_id: 3868289 #2732721
  secure_key: 8f87VdKrVNLYiIRc1QFU #kJ0AVDo3he9GhGlhkmha
  netmoney_to_money: {1 : 10, 3 : 35, 5 : 60, 10 : 140, 50 : 850}

mailru:
  app_id: 666052
  secure_key: 5913a8ff0e9374362dd4dc87605c5e55
  netmoney_to_money: {}

energy:
  time_buffer: 60

friend_daily_bonus:
  time_buffer: 60
