production:
  adapter: mysql
  host: 127.0.0.1
  database: rabbit
  username: rabbit
  password: love4meand663

development:
  adapter: mysql
  host: 127.0.0.1
  database: rabbit_development
  username: rabbit
  password: love4meand663

test:
  adapter: mysql
  host: 127.0.0.1
  database: rabbit_test
  username: rabbit
  password: love4meand663

stat:
  adapter: mysql
  host: 127.0.0.1
  database: rabbit_stat
  username: rabbit
  password: love4meand663
