production:
  adapter: postgresql
  database: rabbit
  username: rabbit
  password: love4meand663
  encoding: utf8
  reconnect: true
  pool: 20

development:
  adapter: postgresql
  database: rabbit
  username: rabbit
  password: love4meand663
  encoding: utf8
  reconnect: true

test:
  adapter: postgresql
  database: rabbit_test
  username: rabbit
  password: love4meand663
  encoding: utf8
  reconnect: true

stat:
  adapter: postgresql
  database: rabbit_stat
  username: rabbit
  password: love4meand663
  encoding: utf8
  reconnect: true
