###############################
#
#	БАЗА ЭЛЕМЕНТОВ ДЛЯ КАСТОМИЗАЦИИ НОРКИ
#	элементы с ID < 0базовые и не могут быть использованы напрямую
#   ids = 1xx
#
###############################
customize: &customize
  <<: *default_item
  id: -100
  class: CustomizeDef
  type: false
  start: false
  shoppable: true

#####################
#
#	КРЫШИ
#
#####################
roof: &roof
  <<: *customize
  type: roof
  id: -102

default_roof:
  <<: *roof
  id: 100
  slug: reward.DefaultRoof
  start: true

tile_roof:
  <<: *roof
  id: 101
  slug: reward.TileRoof
  cost: 50

crab_roof:
  <<: *roof
  id: 102
  slug: reward.CrabRoof
  cost: 40

pirate_roof:
  <<: *roof
  id: 103
  slug: reward.PirateRoof
  cost: 0
  shoppable: false

#####################
#
#	ВОРОТА
#
#####################
door: &door
  <<: *customize
  type: door
  id: -110

default_door:
  <<: *door
  id: 110
  slug: reward.DefaultDoor
  shop_slug: reward.DefaultDoorView
  start: true

wood_door:
  <<: *door
  id: 111
  slug: reward.WoodDoor
  cost: 30

pink_door:
  <<: *door
  id: 112
  slug: reward.PinkDoor
  cost: 40

pirate_door:
  <<: *door
  id: 113
  slug: reward.PirateDoor
  cost: 0
  shoppable: false

#####################
#
#	ТАБЛИЧИК
#
#####################
title: &title
  <<: *customize
  type: title
  id: -120

default_title:
  <<: *title
  id: 120
  slug: reward.DefaultTitle
  start: true

zinc_title:
  <<: *title
  id: 121
  slug: reward.ZincTitle
  cost: 25

pink_title:
  <<: *title
  id: 122
  slug: reward.PinkTitle
  cost: 20

lilac_title:
  <<: *title
  id: 123
  slug: reward.LilacTitle
  cost: 20

#####################
#
#	КОВРИКИ
#
#####################

mat: &mat
  <<: *customize
  type: mat
  id: -130

default_mat:
  <<: *mat
  id: 130
  slug: reward.DefaultMat
  start: true

color_mat:
  <<: *mat
  id: 131
  slug: reward.ColorMat
  cost: 30

board_mat:
  <<: *mat
  id: 132
  slug: reward.BoardMat
  cost: 10

spiral_mat:
  <<: *mat
  id: 133
  slug: reward.SpiralMat
  cost: 20

village_mat:
  <<: *mat
  id: 134
  slug: reward.VillageMat
  cost: 20
