###############################
#
#	БАЗА ЭЛЕМЕНТОВ ДЛЯ КАСТОМИЗАЦИИ НОРКИ
#	элементы с ID < 0базовые и не могут быть использованы напрямую
#   ids = 1xx
#
###############################
customize: &customize
  <<: *default_item
  id: -100
  class: CustomizeDef
  type: false
  start: false

#####################
#
#	КРЫШИ
#
#####################
roof: &roof
  <<: *customize
  type: roof
  id: -102

default_roof:
  <<: *roof
  id: 100
  slug: reward.DefaultRoof
  start: true

tile_roof:
  <<: *roof
  id: 101
  slug: reward.TileRoof

#####################
#
#	ВОРОТА
#
#####################
door: &door
  <<: *customize
  type: door
  id: -110

default_door:
  <<: *door
  id: 110
  slug: reward.DefaultDoor
  start: true

wood_roof:
  <<: *door
  id: 111
  slug: reward.WoodDoor

#####################
#
#	ТАБЛИЧИК
#
#####################
title: &title
  <<: *customize
  type: title
  id: -120

default_title:
  <<: *title
  id: 120
  slug: reward.DefaultTitle
  start: true

zinc_title:
  <<: *title
  id: 121
  slug: reward.ZincTitle
