---
1:
- type: 0
  x: 6
  y: 1
- type: 0
  x: 10
  y: 6
2:
- type: 0
  x: 1
  y: 6
- type: 0
  x: 6
  y: 9
- type: 0
  x: 9
  y: 1
3:
- type: 0
  x: 2
  y: 2
- type: 0
  x: 10
  y: 4
- type: 0
  x: 9
  y: 11
4:
- type: 0
  x: 10
  y: 13
- type: 0
  x: 11
  y: 7
- type: 0
  x: 1
  y: 3
5:
- type: 1
  x: 4
  y: 16
- type: 1
  x: 10
  y: 11
- type: 1
  x: 10
  y: 5
- type: 1
  x: 11
  y: 20
6:
- type: 0
  x: 6
  y: 7
- type: 0
  x: 13
  y: 1
- type: 0
  x: 11
  y: 13
7:
- type: 0
  x: 7
  y: 1
- type: 0
  x: 8
  y: 8
- type: 0
  x: 0
  y: 9
8:
- type: 0
  x: 13
  y: 2
- type: 0
  x: 13
  y: 8
- type: 0
  x: 7
  y: 9
9:
- type: 1
  x: 5
  y: 6
- type: 1
  x: 2
  y: 1
- type: 1
  x: 9
  y: 1
- type: 1
  x: 7
  y: 7
10:
- type: 1
  x: 10
  y: 6
- type: 1
  x: 14
  y: 2
- type: 1
  x: 1
  y: 8
- type: 1
  x: 10
  y: 10
11:
- type: 2
  x: 5
  y: 4
- type: 2
  x: 8
  y: 3
- type: 2
  x: 22
  y: 10
- type: 2
  x: 28
  y: 4
12:
- type: 1
  x: 15
  y: 9
- type: 1
  x: 15
  y: 4
- type: 1
  x: 3
  y: 6
- type: 1
  x: 1
  y: 16
13:
- type: 2
  x: 8
  y: 3
- type: 2
  x: 3
  y: 3
- type: 2
  x: 3
  y: 8
- type: 2
  x: 7
  y: 6
14:
- type: 1
  x: 3
  y: 1
- type: 1
  x: 6
  y: 0
- type: 1
  x: 6
  y: 11
- type: 1
  x: 9
  y: 15
15:
- type: 2
  x: 9
  y: 0
- type: 2
  x: 9
  y: 4
- type: 2
  x: 1
  y: 11
- type: 2
  x: 1
  y: 9
16:
- type: 2
  x: 5
  y: 4
- type: 2
  x: 8
  y: 16
- type: 2
  x: 14
  y: 13
- type: 2
  x: 12
  y: 2
17:
- type: 2
  x: 1
  y: 1
- type: 2
  x: 10
  y: 7
- type: 2
  x: 13
  y: 7
- type: 2
  x: 22
  y: 2
