---
2:
- x: 1
  y: 7
- x: 7
  y: 7
- x: 8
  y: 3
- x: 10
  y: 6
- x: 5
  y: 11
3:
- x: 0
  y: 0
- x: 0
  y: 8
- x: 6
  y: 8
- x: 11
  y: 1
- x: 5
  y: 1
4:
- x: 5
  y: 7
- x: 3
  y: 16
- x: 8
  y: 16
- x: 11
  y: 7
- x: 1
  y: 8
5:
- x: 4
  y: 15
- x: 13
  y: 15
- x: 9
  y: 10
- x: 8
  y: 20
- x: 9
  y: 5
6:
- x: 1
  y: 1
- x: 1
  y: 16
- x: 17
  y: 16
- x: 17
  y: 2
- x: 12
  y: 9
7:
- x: 1
  y: 5
- x: 5
  y: 9
- x: 6
  y: 5
- x: 11
  y: 7
- x: 10
  y: 2
8:
- x: 11
  y: 10
- x: 3
  y: 10
- x: 14
  y: 0
- x: 6
  y: 2
- x: 7
  y: 4
9:
- x: 9
  y: 5
- x: 7
  y: 6
- x: 6
  y: 3
- x: 1
  y: 3
- x: 3
  y: 5
10:
- x: 2
  y: 4
- x: 2
  y: 18
- x: 14
  y: 18
- x: 29
  y: 19
- x: 19
  y: 4
11:
- x: 8
  y: 2
- x: 16
  y: 4
- x: 1
  y: 8
- x: 14
  y: 10
- x: 8
  y: 6
12:
- x: 10
  y: 11
- x: 17
  y: 13
- x: 1
  y: 4
- x: 8
  y: 3
- x: 1
  y: 13
