---
2:
- x: 4
  y: 0
- x: 2
  y: 7
- x: 7
  y: 9
- x: 10
  y: 3
3:
- x: 5
  y: 2
- x: 9
  y: 9
- x: 0
  y: 4
4:
- x: 5
  y: 8
- x: 11
  y: 7
- x: 8
  y: 17
- x: 1
  y: 8
5:
- x: 5
  y: 15
- x: 12
  y: 15
- x: 9
  y: 5
6:
- x: 1
  y: 8
- x: 17
  y: 6
- x: 11
  y: 16
- x: 8
  y: 1
7:
- x: 1
  y: 6
- x: 11
  y: 7
- x: 10
  y: 0
8:
- x: 12
  y: 2
- x: 3
  y: 7
- x: 1
  y: 10
- x: 8
  y: 0
9:
- x: 5
  y: 6
- x: 1
  y: 3
- x: 11
  y: 6
10:
- x: 4
  y: 7
- x: 14
  y: 16
- x: 24
  y: 12
- x: 23
  y: 18
11:
- x: 1
  y: 8
- x: 16
  y: 3
- x: 10
  y: 2
12:
- x: 17
  y: 12
- x: 1
  y: 4
- x: 5
  y: 4
- x: 11
  y: 16
13:
- x: 5
  y: 6
- x: 3
  y: 4
- x: 8
  y: 3
- x: 7
  y: 7
- x: 7
  y: 2
- x: 2
  y: 7
14:
- x: 6
  y: 12
- x: 10
  y: 5
- x: 6
  y: 1
- x: 3
  y: 1
- x: 3
  y: 12
- x: 11
  y: 14
15:
- x: 9
  y: 1
- x: 4
  y: 1
- x: 2
  y: 11
- x: 0
  y: 5
- x: 9
  y: 4
- x: 10
  y: 10
16:
- x: 1
  y: 16
- x: 7
  y: 13
- x: 7
  y: 7
- x: 13
  y: 4
- x: 4
  y: 7
- x: 16
  y: 1
17:
- x: 9
  y: 4
- x: 14
  y: 14
- x: 8
  y: 16
- x: 17
  y: 2
- x: 17
  y: 11
- x: 8
  y: 12
18:
- x: 7
  y: 7
- x: 8
  y: 16
- x: 14
  y: 10
- x: 11
  y: 4
- x: 0
  y: 13
- x: 0
  y: 0
19:
- x: 8
  y: 2
- x: 19
  y: 6
- x: 11
  y: 15
- x: 3
  y: 7
- x: 0
  y: 6
- x: 10
  y: 5
20:
- x: 4
  y: 10
- x: 8
  y: 6
- x: 13
  y: 7
- x: 16
  y: 2
- x: 10
  y: 1
- x: 4
  y: 1
21:
- x: 4
  y: 7
- x: 7
  y: 3
- x: 9
  y: 4
- x: 13
  y: 7
- x: 19
  y: 1
- x: 22
  y: 2
22:
- x: 6
  y: 3
- x: 9
  y: 4
- x: 11
  y: 2
- x: 4
  y: 11
- x: 4
  y: 5
- x: 6
  y: 9
- x: 9
  y: 11
23:
- x: 2
  y: 11
- x: 10
  y: 11
- x: 0
  y: 6
- x: 8
  y: 8
- x: 7
  y: 11
- x: 11
  y: 4
- x: 3
  y: 11
24:
- x: 5
  y: 10
- x: 1
  y: 1
- x: 13
  y: 0
- x: 18
  y: 10
- x: 25
  y: 7
- x: 33
  y: 11
- x: 36
  y: 11
- x: 51
  y: 7
- x: 57
  y: 10
- x: 62
  y: 10
- x: 58
  y: 1
- x: 62
  y: 2
