---
1:
- type: 0
  x: 8
  y: 6
- type: 0
  x: 11
  y: 1
2:
- type: 0
  x: 0
  y: 10
- type: 0
  x: 7
  y: 8
- type: 0
  x: 9
  y: 1
3:
- type: 0
  x: 10
  y: 4
- type: 0
  x: 3
  y: 0
- type: 0
  x: 0
  y: 8
4:
- type: 0
  x: 1
  y: 17
- type: 0
  x: 10
  y: 14
- type: 0
  x: 9
  y: 1
5:
- type: 0
  x: 15
  y: 3
- type: 0
  x: 1
  y: 3
- type: 0
  x: 7
  y: 15
6:
- type: 0
  x: 5
  y: 12
- type: 0
  x: 16
  y: 4
- type: 0
  x: 13
  y: 11
7:
- type: 1
  x: 1
  y: 5
- type: 1
  x: 6
  y: 5
- type: 1
  x: 3
  y: 11
8:
- type: 0
  x: 3
  y: 7
- type: 0
  x: 8
  y: 0
- type: 0
  x: 13
  y: 8
9:
- type: 1
  x: 11
  y: 5
- type: 1
  x: 4
  y: 4
- type: 1
  x: 3
  y: 3
10:
- type: 1
  x: 12
  y: 6
- type: 1
  x: 14
  y: 10
11:
- type: 1
  x: 8
  y: 6
- type: 1
  x: 20
  y: 16
- type: 1
  x: 6
  y: 6
12:
- type: 1
  x: 6
  y: 5
- type: 1
  x: 1
  y: 16
- type: 1
  x: 11
  y: 16
13:
- type: 1
  x: 3
  y: 2
- type: 1
  x: 3
  y: 8
- type: 1
  x: 8
  y: 3
14:
- type: 1
  x: 10
  y: 3
- type: 1
  x: 1
  y: 8
- type: 1
  x: 6
  y: 13
