# интервал в днях между возможностью собирать монетки у друзей
FRIEND_DAILY_BONUS_INTERVAL: 86400 # day
VISIT_REWARD_MONEY: 1
INVITE_REWARD_MONEY: 5
DEFAULT_LOCALE: ru
ENERGY_GAIN_INTERVAL: 10800
ENERGY_MAX: 5
ENERGY_COST: 3